name:="Simple Project"
version:="1.0"
scalaVersion:="2.12.18"
libraryDependencies+="org.apache.spark" %% "spark-core" % "3.5.1"
libraryDependencies += "org.apache.spark" %% "spark-graphx" % "3.5.1"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.5.1"